version: '3.8'

services:
  atk-nginx:
    build:
      context: ./atk-nginx
      dockerfile: Dockerfile
    container_name: atk-nginx
    networks:
      - atk-net
    ports:
      - "8080:80"
    volumes:
      - ./atk-nginx/conf.d:/usr/share/nginx/conf.d
      - ./atk-nginx/html:/usr/share/nginx/html

  atk-ingest:
    build:
      context: ./atk-ingest
      dockerfile: Dockerfile
    container_name: atk-ingest
    networks:
      - atk-net
    ports:
      - "8443:443"
    volumes:
      - ./atk-ingest/conf.d:/etc/nginx/conf.d

  atk-auth:
    image: docker.io/authelia/authelia:latest
    container_name: atk-auth
    networks:
      - atk-net
    ports:
      - "9091:9091"
    environment:
      AUTHELIA_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
    volumes:
      - ./atk-auth/config:/config

networks:
  atk-net:
    driver: bridge
