host: 0.0.0.0
port: 9091

log_level: info

authentication_backend:
  disable_reset_password: false
  file:
    path: /etc/authelia/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: auth.atk.net
      policy: two_factor

session:
  secret: your_secret_here
  expiration: 3600
  inactivity: 300

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

